### ISSUE TITLE
Fix syntax error in example code

### ISSUE THREAD

**Issue by vellip** [walsh9/videojs-transcript#11]
Hey,

in your example code in the readme there's a syntax error in your JavaScript. You have a parenthese gone wrong. 

```  js
var video = videojs('video').ready(function(){
      // Set up any options.
      var options = {
        showTitle: false,
        showTrackSelector: false,
      }); <---
 ```
There is no parenthese needed there, as it is just an object literal.

**Comment by walsh9** [comment]
Good catch. Thanks!
